TeacherOnline/Controllers/EstimateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Runtime.Intrinsics.X86;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.DAL;
using TeacherOnline.DAL.Entities;
using TeacherOnline.DTO.ViewModel;
using TeacherOnline.Models;
using static TeacherOnline.DTO.ViewModel.EstimateVM;

namespace TeacherOnline.Controllers
{
    public class EstimateController : Controller
    {
        IProfile _profile;
        IGroup _group;
        ISubject _subject;
        IEstimate _estimate;
        IGroupsInSub _groupsInSub;

        public EstimateController(IGroup group, ISubject subject, IProfile profile, IEstimate estimate, IGroupsInSub groupsInSub)
        {
            _group = group;
            _subject = subject;
            _profile = profile;
            _estimate = estimate;
            _groupsInSub = groupsInSub;
        }

        //-------------------------------------------------------------------------------------------
        //Method Get

        [HttpGet]
        public IActionResult Index(int selectedSubject, int selectedUser, SortStateEstimate sortOrder = SortStateEstimate.DateAddDesc)
        {
            ViewData["Id"] = (int)HttpContext.Session.GetInt32("Id");
            var vm = new EstimateVM();
            if(selectedSubject == 0 && selectedUser == 0)
            {
                if (User.IsInRole("Teacher"))
                    vm.estimateList = _estimate.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id"));
                else
                    vm.estimateList = _estimate.Find(u => u.IdUser == (int)HttpContext.Session.GetInt32("Id"));
            }
            else if(selectedSubject != 0 && selectedUser == 0)
            {
                if (User.IsInRole("Teacher"))
                    vm.estimateList = _estimate.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id") && u.IdSubject == selectedSubject);
                else
                    vm.estimateList = _estimate.Find(u => u.IdUser == (int)HttpContext.Session.GetInt32("Id") && u.IdSubject == selectedSubject);
                vm.subject = _subject.Get(selectedSubject);
            }
            else if(selectedSubject == 0 && selectedUser != 0 && User.IsInRole("Teacher"))
            {
                vm.estimateList = _estimate.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id") && u.IdUser == selectedUser);
                vm.subject = _subject.Get(selectedSubject);
            }
            else
            {
                vm.estimateList = _estimate.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id") 
                && u.IdUser == selectedUser && u.IdSubject == selectedSubject);
                vm.subject = _subject.Get(selectedSubject);
            }


            vm.subjects = _estimate.Find(u=> u.IdUser == (int)HttpContext.Session.GetInt32("Id") || u.IdTeacher == (int)HttpContext.Session.GetInt32("Id"))
                                   .Select(u=> u.IdSubjectNavigation);
            foreach(var item in vm.subjects)
            {
                if (!vm.DisplaySubj.ContainsKey(item.Id))
                {
                    vm.DisplaySubj.Add(item.Id, item.Name);
                    continue;
                }
                else continue;
            }

            if (User.IsInRole("Teacher"))
            {
                vm.users = _estimate.Find(u=> u.IdUser == (int)HttpContext.Session.GetInt32("Id") || u.IdTeacher == (int)HttpContext.Session.GetInt32("Id"))
                                       .Select(u=> u.IdUserNavigation);
                foreach(var item in vm.users)
                {
                    if (!vm.DisplayUser.ContainsKey(item.Id))
                    {
                        vm.DisplayUser.Add(item.Id, fioUser(item));
                        continue;
                    }
                    else continue;
                }
            }

            ViewData["IdSubSort"] = sortOrder == SortStateEstimate.IdSubAsc ? SortStateEstimate.IdSubDesc : SortStateEstimate.IdSubAsc;
            ViewData["ScoreSort"] = sortOrder == SortStateEstimate.ScoreAsc ? SortStateEstimate.ScoreDesc : SortStateEstimate.ScoreAsc;
            ViewData["DateAddSort"] = sortOrder == SortStateEstimate.DateAddAsc ? SortStateEstimate.DateAddDesc : SortStateEstimate.DateAddAsc;
            vm.estimateList = sortOrder switch
            {
                SortStateEstimate.IdSubDesc => vm.estimateList.OrderByDescending(u => u.IdSubject),
                SortStateEstimate.ScoreAsc => vm.estimateList.OrderBy(u => u.Score),
                SortStateEstimate.ScoreDesc => vm.estimateList.OrderByDescending(u => u.Score),
                SortStateEstimate.DateAddAsc => vm.estimateList.OrderBy(u => u.DateAdd),
                SortStateEstimate.DateAddDesc => vm.estimateList.OrderByDescending(u => u.DateAdd),
                _ => vm.estimateList.OrderBy(u => u.IdSubject)
            };
            vm.estimateList.AsQueryable().AsNoTracking();
            vm.Str = new Sorted(sortOrder);
            vm.Fltr = new Filters(selectedSubject, selectedUser);
            return View(vm);
        }

        public string fioUser(Profile profile)
        {
            string fioUser = $"{profile.LastName} {profile.FirstName}";
            return fioUser;
        }

        [HttpGet]
        [Authorize(Roles ="Teacher")]
        public IActionResult CreateEstimate()
        {
            var vm = new EstimateVM();
            vm.groups = _group.GetAll();
            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public IActionResult UpdateEstimate(int id)
        {
            var vm = new EstimateVM();
            vm.estimate = _estimate.Get(id);
            //алгоритм изьятия студента, зная номер предмета
            vm.OneGroup = _groupsInSub.Get(u => u.IdSubject == vm.estimate.IdSubject).IdGroupsNavigation;
            vm.users = _profile.Find(u => u.IdNavigation.Rank == "Study" && u.Groups == vm.OneGroup.Id);

            vm.groups = _group.GetAll();
            vm.subjects = _groupsInSub.Find(u =>u.IdGroups == vm.OneGroup.Id && u.IdSubjectNavigation.IdTeacher == (int)HttpContext.Session.GetInt32("Id")).Select(u=>u.IdSubjectNavigation);
            return View(vm);
        }

        [HttpGet]
        public IActionResult AverageEstimate(int id, int idgroup)
        {
            var vm = new EstimateVM();
            vm.OneGroup = _groupsInSub.Get(u => u.IdSubject == id && u.IdGroups == idgroup).IdGroupsNavigation;
            vm.users = _profile.Find(u => u.IdNavigation.Rank == "Study" && u.Groups == idgroup);
            vm.subject = _subject.Get(id);
            vm.estimateList = _estimate.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id") || u.IdSubject == id)
                .OrderBy(u => u.IdUserNavigation.LastName);
            List<Estimate> tempList = vm.estimateList.OrderBy(u => u.IdUser).ToList();
            int currentUser = 0;
            //var estList = AvgEst(vm, tempList, currentUser, id);
            vm.AvgEstimate = AvgEst(vm, tempList, currentUser, id);
            //vm.CountEstTeory = CountEstimateTeoty(vm.estimateList);
            return View(vm);
        }
        [HttpGet]
        public IActionResult GetStats(int id)
        {
            var vm = new EstimateVM();
            vm.user = _profile.Get(id);
            vm.subjects = _groupsInSub.Find(u => u.IdGroups == vm.user.Groups).Select(u => u.IdSubjectNavigation);
            return View(vm);
        }

        [HttpGet]
        public IActionResult GetStat(EstimateVM vm)
        {
            vm.estimateList = _estimate.Find(u => u.IdSubject == vm.subject.Id && u.IdUser == vm.user.Id);
            vm.user = _profile.Get(vm.user.Id);
            vm.subjects = _groupsInSub.Find(u=> u.IdGroups == vm.user.Groups).Select(u=>u.IdSubjectNavigation);
            vm.subject = _subject.Get(vm.subject.Id);
            vm.CountEstTeory = CountEstimateTeoty(vm.estimateList);
            vm.CountEstPrakt = CountEstimatePrakt(vm.estimateList);
            vm.CountEstOKR = CountEstimateOKR(vm.estimateList);
            vm.AvgEstimate = AvgEstToUser(vm.estimateList.ToList(), vm.user.Id, vm.subject.Id, vm.AvgEstimate);
            return View("GetStats", vm);
        }

        //Helps method
        private Dictionary<int,int> CountEstimateTeoty(IEnumerable<Estimate> list)
        {
            EstimateVM vm = new EstimateVM();
            foreach (var item in list)
            {
                if(item.Type == 0)
                {
                    if (vm.CountEstTeory.IsNullOrEmpty())
                    {
                        vm.CountEstTeory.Add(item.Score, 1);
                        continue;
                    }
                    if (vm.CountEstTeory.ContainsKey(item.Score))
                    {
                        vm.CountEstTeory[item.Score]++;
                        continue;
                    }
                    else
                    {
                        vm.CountEstTeory.Add(item.Score, 1);
                        continue;
                    }
                }
                continue;
            }
            return vm.CountEstTeory;
        }
        private Dictionary<int, int> CountEstimatePrakt(IEnumerable<Estimate> list)
        {
            EstimateVM vm = new EstimateVM();
            foreach (var item in list)
            {
                if (item.Type == 1)
                {
                    if (vm.CountEstPrakt.IsNullOrEmpty())
                    {
                        vm.CountEstPrakt.Add(item.Score, 1);
                        continue;
                    }
                    if (vm.CountEstPrakt.ContainsKey(item.Score))

TeacherOnline/Views/Estimate/AverageEstimate.cshtml
@{
    ViewData["Title"] = Model.subject.Name;
}
@functions {
    public string fioUser(TeacherOnline.DAL.Entities.Profile profile)
    {
        string fioUser = $"{profile.LastName} {profile.FirstName}";
        return fioUser;
    }
}
@model TeacherOnline.DTO.ViewModel.EstimateVM;

<h1>@ViewData["Title"]</h1>


<table class="table">
    <thead>
        <tr>
            <th scope="col">Учащийся</th>
            <th scope="col">Отметка за семестр</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.users)
        {
            <tr>
                <td>@fioUser(item)</td>
                @if (Double.IsNaN(Model.AvgEstimate[item.Id]))
                {
                    <td>нет отметки</td>
                }
                else
                {
                    <td>@Model.AvgEstimate[item.Id]</td>
                }
            </tr>
        }
    </tbody>
</table>

TeacherOnline/Views/Estimate/CreateEstimate.cshtml
@{
    ViewData["Title"] = "Создать отметку";

}
@functions {
    public string fioUser(TeacherOnline.DAL.Entities.Profile profile)
    {
        string fioUser = $"{profile.LastName} {profile.FirstName[0]}. {profile.Otchestvo[0]}.";
        return fioUser;
    }
    public string fioTeacher(TeacherOnline.DAL.Entities.Profile profile)
    {
        string fioTeacher = $"{profile.LastName} {profile.FirstName[0]}. {profile.Otchestvo[0]}.";
        return fioTeacher;
    }
}
@model TeacherOnline.DTO.ViewModel.EstimateVM;
<h2>@ViewData["Title"]</h2>

<form asp-controller="Estimate" asp-action="CreateEstimate" method="post">
    <div class="mb-3">
        <div class="col-md-3">
            <label for="inputDepartment" class="form-label">Группа</label>
            <select required id="Group" class="form-select" onchange="LoadDLOnSubject(this, 'Subject', 'Users');">
                <option selected disabled value="">Выберите группу</option>
                @foreach (var item in Model.groups)
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>
        <div class="col-md-3">
            <label for="inputDepartment" class="form-label">Предмет</label>
            <select required id="Subject" class="form-select" onchange="LoadDLOnUsers(this, 'Users')" asp-for="@Model.estimate.IdSubject"></select>
        </div>
        <div class="col-md-3">
            <label for="inputDepartment" class="form-label">Учащийся</label>
            <select required id="Users" class="form-select" asp-for="@Model.estimate.IdUser"></select>
        </div>
        <div class="col-md-3">
            <label for="inputDepartment" class="form-label">Тип отметки</label>
            <select required id="Users" class="form-select" asp-for="@Model.estimate.Type">
                @foreach(var item in Model.TypeEstimate)
                {
                    <option value="@item.Key">@item.Value</option>
                }
            </select>
        </div>
        <label class="form-label">Отметка: <output id="value"></output></label>
        <input required type="range" class="form-range" min="1" max="10" id="estInput" asp-for="@Model.estimate.Score">
    </div>
    <button type="submit" class="btn btn-outline-success">Создать отметку</button>
</form>


@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">

        const value = document.querySelector("#value")
        const input = document.querySelector("#estInput")
        value.textContent = input.value
        input.addEventListener("input", (event) => {
            value.textContent = event.target.value
        })


        var tempGroupId = 0;
        function LoadDLOnUsers(SubjectId, htmlIdUsers) {
            var listUser = $("#" + htmlIdUsers);
            listUser.empty();
            listUser.append($('<option/>',
                {
                    value: null,
                    text: "Выберите студента"
                }));
            $(listUser[0][0]).attr('disabled', true);
            $(listUser[0][0]).attr('selected', true);
            var selectedSubject = SubjectId.options[SubjectId.selectedIndex].value;
            var selectedGroup = tempGroupId.options[tempGroupId.selectedIndex].value;
            if (selectedSubject != null && selectedSubject != '' && selectedGroup != null && selectedGroup != '') {
                $.getJSON('@Url.Action("GetUserBySubject")', { subjectId: selectedSubject, groupId: selectedGroup }, function (users) {
                    if (users != null && !jQuery.isEmptyObject(users)) {
                        $.each(users, function (index, user) {
                            listUser.append($('<option/>', {
                                value: user.value,
                                text: user.text
                            }));
                        });
                    };
                });
            };
        };
        function LoadDLOnSubject(GroupId, htmlIdSubject, htmlIdUsers) {
            tempGroupId = GroupId;
            var listubject = $("#" + htmlIdSubject);
            listubject.empty();
            listubject.append($('<option/>',
                {
                    value: null,
                    text: "Выберите предмет"
                }));
            $(listubject[0][0]).attr('disabled', true);
            $(listubject[0][0]).attr('selected', true);
            var listUser = $("#" + htmlIdUsers);
            listUser.empty();
            var selectedGroup = GroupId.options[GroupId.selectedIndex].value;
            if (selectedGroup != null && selectedGroup != '') {
                $.getJSON('@Url.Action("GetSubjectOnGroup")', { groupId: selectedGroup }, function (subjects) {
                    if (subjects != null && !jQuery.isEmptyObject(subjects)) {
                        $.each(subjects, function (index, subject) {
                            listubject.append($('<option/>', {
                                value: subject.value,
                                text: subject.text
                            }));
                        });
                    };
                });
            };
        };
    </script>
}

TeacherOnline/Views/Estimate/GetStats.cshtml
@{
    ViewData["Title"] = "";
}
@functions {
    public string fioUser(TeacherOnline.DAL.Entities.Profile profile)
    {
        string fioUser = $"{profile.LastName} {profile.FirstName}";
        return fioUser;
    }
}
@model TeacherOnline.DTO.ViewModel.EstimateVM;

<h1>Статистика @fioUser(Model.user) по предмету @Model.subject?.Name</h1>
@{
    //var data = Json.Serialize(Model.CountEst.Keys.OrderBy(u=> u));
    SortedDictionary<int, int> dataT = new SortedDictionary<int, int>();
    SortedDictionary<int, int> dataP = new SortedDictionary<int, int>();
    SortedDictionary<int, int> dataO = new SortedDictionary<int, int>();
    if(Model.CountEstTeory.Count > 0)
    {
        dataT = new SortedDictionary<int, int>(Model.CountEstTeory);
    }
    if(Model.CountEstPrakt.Count > 0)
    {
        dataP = new SortedDictionary<int, int>(Model.CountEstPrakt);
    }
    if(Model.CountEstOKR.Count > 0)
    {
        dataO = new SortedDictionary<int, int>(Model.CountEstOKR);
    }
}

<form method="get" class="hstack gap-3 m-3" asp-controller="Estimate" asp-action="GetStat">
    <input type="hidden" value="@Model.user.Id" asp-for="@Model.user.Id"/>
    <label>Предмет для статистики:</label>
    <select required class="form-select" asp-for="@Model.subject.Id">
        @foreach(var item in Model.subjects)
        {
            if(item.Id == Model.subject?.Id)
            {
                <option selected value="@item.Id">@item.Name</option>
                continue;
            }
            <option value="@item.Id">@item.Name</option>
        }
    </select>
    <button type="submit" class="btn btn-outline-primary">Показать статистику</button>
</form>





@*<p> @Json.Serialize(tempdata.Keys) @Json.Serialize(tempdata.Values) </p>*@
@if (dataT.Count > 0 || dataP.Count > 0 || dataO.Count > 0)
{
    <div class="container">
        <h3>Теория</h3>
        <canvas id="ChartEstTeory" width="600" height="150"></canvas>
    </div>
    <div class="container">
        <h3>Практика</h3>
        <canvas id="ChartEstPrakt" width="600" height="150"></canvas>
    </div>
    <div class="container">
        <h3>Контрольная</h3>
        <canvas id="ChartEstOKR" width="600" height="150"></canvas>
    </div>
    <div>
        <h1>Средний бал за предмет:@Model.AvgEstimate.GetValueOrDefault(Model.user.Id)</h1>
    </div>
}

@section Scripts{
   @* <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>*@
    @*<script src="
https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js
"></script>*@

<script src="~/js/chart/chart.umd.min.js"></script>
    <script type="text/javascript">
        const ctxTeory = document.getElementById('ChartEstTeory');
        const ctxPrakt = document.getElementById('ChartEstPrakt');
        const ctxOKR = document.getElementById('ChartEstOKR');
        //const arr = Array.from({length: 10}, (_, index) => index + 1);
        const chartTeory = new Chart(ctxTeory, {
            type: 'bar',
            data: {
                labels: @Json.Serialize(dataT.Keys) ,
                datasets: [{
                    label: 'Отметки',
                    data: @Json.Serialize(dataT.Values) ,
                    borderWidth: 1
                }]
            },
            option:{
                scales: {
                    y: {
                    beginAtZero: true
                    }
                }
            }
        });
        const chartPrakt = new Chart(ctxPrakt, {
            type: 'bar',
            data: {
                labels: @Json.Serialize(dataP.Keys) ,
                datasets: [{
                    label: 'Отметки',
                    data: @Json.Serialize(dataP.Values) ,
                    borderWidth: 1
                }]
            },
            option:{
                scales: {
                    y: {
                    beginAtZero: true
                    }
                }
            }
        });
        const chartOKR = new Chart(ctxOKR, {
            type: 'bar',
            data: {
                labels: @Json.Serialize(dataO.Keys) ,
                datasets: [{
                    label: 'Отметки',
                    data: @Json.Serialize(dataO.Values) ,
                    borderWidth: 1
                }]
            },
            option:{
                scales: {
                    y: {
                    beginAtZero: true
                    }
                }
            }
        });
    </script>
}

TeacherOnline/Views/Estimate/Index.cshtml
@{
    ViewData["Title"] = "Отметки";
}
@functions{
    public string fioUser(TeacherOnline.DAL.Entities.Estimate estimate)
    {
        string fioUser = $"{estimate.IdUserNavigation.LastName} {estimate.IdUserNavigation.FirstName[0]}. {estimate.IdUserNavigation.Otchestvo[0]}.";
        return fioUser;
    }
    public string fioTeacher(TeacherOnline.DAL.Entities.Estimate estimate)
    {
        string fioTeacher = $"{estimate.IdTeacherNavigation.LastName} {estimate.IdTeacherNavigation.FirstName[0]}. {estimate.IdTeacherNavigation.Otchestvo[0]}.";
        return fioTeacher;
    }
}
@model TeacherOnline.DTO.ViewModel.EstimateVM;

<h1>@ViewData["Title"]</h1>
@if (User.IsInRole("Teacher"))
{
    <a class="btn btn-outline-primary m-3" asp-controller="Estimate" asp-action="CreateEstimate">Создать отметку<br /></a>
}
<form method="get" class="hstack gap-3 m-3" asp-action="Index" asp-controller="Estimate">
    <select required name="selectedSubject" class="form-select" asp-for="@Model.Fltr.SelectedSubject">
        <option >Все отметки</option>
        @foreach (var item in Model.DisplaySubj)
        {
            if(item.Key == Model.subject?.Id)
            {
                <option selected value="@item.Key">@item.Value</option>
                continue;
            }
            <option value="@item.Key">@item.Value</option>
        }
    </select>
    @if (User.IsInRole("Teacher"))
    {
        <select required name="selectedUser" class="form-select" asp-for="@Model.Fltr.SelectedUser">
            <option value="0">Все учащиеся</option>
            @foreach (var item in Model.DisplayUser)
            {
                if(item.Key == Model.user?.Id)
                {
                    <option selected value="@item.Key">@item.Value</option>
                    continue;
                }
                <option value="@item.Key">@item.Value</option>
            }
        </select>
    }
    <button type="submit" class="btn btn-outline-primary">Поиск</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th scope="col"><a asp-action="Index" 
                asp-route-selectedSubject="@Model.Fltr.SelectedSubject"
                asp-route-selectedUser="@Model.Fltr.SelectedUser"
                asp-route-sortOrder="@Model.Str.IdSubSort">Предмет</a></th>
            <th scope="col">Учащийся</th>
            <th scope="col"><a asp-action="Index" 
                asp-route-selectedSubject="@Model.Fltr.SelectedSubject"
                asp-route-selectedUser="@Model.Fltr.SelectedUser"
                asp-route-sortOrder="@Model.Str.ScoreSort">Отметка</a></th>
            <th scope="col">Тип отметки</th>
            <th scope="col"><a asp-action="Index" 
                asp-route-selectedSubject="@Model.Fltr.SelectedSubject"
                asp-route-selectedUser="@Model.Fltr.SelectedUser"
                asp-route-sortOrder="@Model.Str.DataAddSort">Дата добавления</a></th>
            <th scope="col">Дата обновления</th>
            <th scope="col">Преподаватель</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.estimateList)
        {
            <tr>
                <th scope="row">@item.IdSubjectNavigation.Name</th>
                <td>@fioUser(item)</td>
                <td>@item.Score</td>
                <td>@Model.TypeEstimate.First(u=>u.Key == item.Type).Value</td>
                <td>@item.DateAdd</td>
                <td>@item.DateUpdate</td>
                <td>@fioTeacher(item)</td>
                @if(item.IdTeacher == (int)ViewData["Id"])
                {
                    <td><a class="btn btn-outline-warning" asp-controller="Estimate" asp-action="UpdateEstimate" asp-route-id="@item.Id">Изменить</a></td>
                    <td>
                        <form method="post" asp-controller="Estimate" asp-action="DeleteEstimate" asp-route-id="@item.Id">
                            <button class="btn btn-outline-danger" type="submit">Удалить</button>
                        </form>
                    </td> 
                }
            </tr>
        }
    </tbody>
</table>