TeacherOnline/Controllers/ChatController.cs
using AutoMapper.Configuration.Annotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.BLL.SignalR;
using TeacherOnline.DAL;
using TeacherOnline.DAL.Entities;
using TeacherOnline.DTO.ViewModel;
using TeacherOnline.Models;

namespace TeacherOnline.Controllers
{
    public class ChatController : Controller
    {
        IProfile _profile;
        IChat _chat;
        IMessage _message;

        public ChatController(IProfile profile, IChat chat, IMessage message)
        {
            _profile = profile;
            _chat = chat;
            _message = message;
        }

        //-------------------------------------------------------------------------------------------
        //Method Get

        [HttpGet]
        public IActionResult Index(int id)
        {
            ViewData["Id"] = HttpContext.Session.GetInt32("Id");
            var chat = _chat.Get(id);
            return View(chat);
        }

        [HttpGet]
        public IActionResult Users()
        {
            var chat = _chat.Find(u => u.IdUser1 == (int)HttpContext.Session.GetInt32("Id")
            || u.IdUser2 == (int)HttpContext.Session.GetInt32("Id")).ToList();
            ViewData["Id"] = HttpContext.Session.GetInt32("Id");
            return View(chat);
        }


        [HttpPost]
        public IActionResult CreateRoom(int Id)
        {
            var chat = new Chat()
            {
                IdUser1 = (int)HttpContext.Session.GetInt32("Id"),
                IdUser2 = Id
            };
            var temp = _chat.Get(u=> (u.IdUser1 == Id ||  u.IdUser2 == Id) 
                        && (u.IdUser1 == (int)HttpContext.Session.GetInt32("Id") || u.IdUser2 == (int)HttpContext.Session.GetInt32("Id")));
            int id;
            if(temp == null)
            {
                id = _chat.Create(chat);
            }
            else
            {
                id = _chat.Get(temp.Id).Id;
            }
            return RedirectToAction("Index", new { id });
        }

        [HttpPost]
        public async  Task<IActionResult> SendMessage(int chatId,string message, [FromServices] IHubContext<ChatHub> chats)
        {
            //тут валидация должна быть.... или на фронте....
            var mes = new Message
            {
                IdAuthor = (int)HttpContext.Session.GetInt32("Id"),
                Message1 = message,
                IdChat = chatId,
                Time = DateTime.Now
            };
            var updateMes = _message.Create(mes);
            await chats.Clients.Group(chatId.ToString()).SendAsync("ReceiveMessage", new
            {
                Text = updateMes.Message1,
                Name = $"{updateMes.IdAuthorNavigation.LastName} {updateMes.IdAuthorNavigation.FirstName}" ,
                Timestamp = updateMes.Time.ToString("hh:mm dd.MM.yy")
            });
            return Ok();
        }


        //-------------------------------------------------------------------------------------------

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeacherOnline/Controllers/GroupController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.DAL;
using TeacherOnline.DAL.Entities;
using TeacherOnline.DTO.ViewModel;
using TeacherOnline.Models;
using static TeacherOnline.DTO.ViewModel.GroupInSubVM;

namespace TeacherOnline.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class GroupController : Controller
    {
        IGroup _group;
        IGroupsInSub _groupInSub;
        ISubject _subject;
        
        public GroupController(IGroup group, IGroupsInSub groupInSub, ISubject subject)
        {
            _group = group;
            _groupInSub = groupInSub;
            _subject = subject;
        }

        //-------------------------------------------------------------------------------------------
        //Method Get

        [HttpGet]
        public IActionResult Index()
        {
            GroupInSubVM vm = new GroupInSubVM();
            vm.groups = _group.GetAll();
            return View(vm);
        }

        public IActionResult CreateGroup()
        {
            return View();
        }

        public IActionResult UpdateGroup(int id)
        {
            return View(_group.Get(id));
        }

        [HttpGet]
        public IActionResult GroupInSub(SortStateGroupInSub sortOrder = SortStateGroupInSub.NameAsc)
        {
            ViewData["Id"] = HttpContext.Session.GetInt32("Id");
            GroupInSubVM vm = new GroupInSubVM();
            vm.gisList = _groupInSub.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id"));

            ViewData["GroupIdSubSort"] = sortOrder == SortStateGroupInSub.NameAsc ? SortStateGroupInSub.NameDesc : SortStateGroupInSub.NameAsc;
            ViewData["IdGroupSort"] = sortOrder == SortStateGroupInSub.IdGroupAsc ? SortStateGroupInSub.IdGroupDesc : SortStateGroupInSub.IdGroupAsc;
            vm.gisList = sortOrder switch
            {
                SortStateGroupInSub.NameDesc => vm.gisList.OrderByDescending(u => u.IdSubjectNavigation.Name),
                SortStateGroupInSub.IdGroupAsc => vm.gisList.OrderBy(u => u.IdGroupsNavigation.Name),
                SortStateGroupInSub.IdGroupDesc => vm.gisList.OrderByDescending(u => u.IdGroupsNavigation.Name),
                _ => vm.gisList.OrderBy(u => u.IdSubjectNavigation.Name)
            };
            vm.gisList.AsQueryable().AsNoTracking();

            return View(vm);
        }

        public IActionResult CreateGroupInSub()
        {
            GroupInSubVM vm = new GroupInSubVM();
            vm.groups = _group.GetAll();
            vm.subjects = _subject.Find(u=> u.IdTeacher == (int)HttpContext.Session.GetInt32("Id"));
            return View(vm);
        }
        
        public IActionResult UpdateGroupInSub(int id)
        {
            GroupInSubVM vm = new GroupInSubVM();
            vm.groupsInSub = _groupInSub.Get(id);
            vm.groups = _group.GetAll();
            vm.subjects = _subject.Find(u => u.IdTeacher == (int)HttpContext.Session.GetInt32("Id"));
            return View(vm);
        }


        //-------------------------------------------------------------------------------------------
        //Method Post


        [HttpPost]
        public IResult CreateGroup(Group vm)
        {
            _group.Create(vm);
            return Results.Redirect("Index");
        }

        [HttpPost]
        public IActionResult DeleteGroup(int id)
        {
            _group.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateGroup(Group vm)
        {
            _group.Update(vm);
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public IResult CreateGroupInSub(GroupInSubVM vm)
        {
            vm.groupsInSub.IdTeacher = (int)HttpContext.Session.GetInt32("Id");
            _groupInSub.Create(vm.groupsInSub);
            return Results.Redirect("GroupInSub");
        }

        [HttpPost]
        public IActionResult DeleteGroupInSub(int id)
        {
            _groupInSub.Delete(id);
            return RedirectToAction("GroupInSub");
        }

        [HttpPost]
        public IActionResult UpdateGroupInSub(GroupInSubVM vm)
        {
            vm.groupsInSub.IdTeacher = (int)HttpContext.Session.GetInt32("Id");
            _groupInSub.Update(vm.groupsInSub);
            return RedirectToAction("GroupInSub");
        }


        //-------------------------------------------------------------------------------------------

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeacherOnline/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using TeacherOnline.Models;
using TeacherOnline.DAL.Entities;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.DTO.ViewModel;
using TeacherOnline.DTO;

namespace TeacherOnline.Controllers
{
    public class UsersController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        IUser _user;
        IProfile _profile;
        IAuth _auth;
        IGroup _group;
        IConvertModels _convert;

        public UsersController(ILogger<HomeController> logger, IUser user, IProfile profile, IAuth auth, IGroup group, IConvertModels convert)
        {
            _logger = logger;
            _user = user;
            _profile = profile;
            _auth = auth;
            _group = group;
            _convert = convert;
        }

        //-------------------------------------------------------------------------------------------
        //Method Get

        [HttpGet]
        public IActionResult Autorization()
        {

            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Study, Teacher")] //тут же добавиться только авторизированным пользователям
        public  IActionResult UserProfile()
        {
            UserProfileVM vm = new UserProfileVM();
            vm.Group = _group.GetAll();
            vm.Profile = _profile.Get((int)HttpContext.Session.GetInt32("Id"));
            if (vm.Profile is null) return RedirectToAction("CreateProfile");
            return View(vm);
        }

        [HttpGet]
        public IActionResult CheckProfile(int id)
        {
            ViewData["Id"] = (int)HttpContext.Session.GetInt32("Id");
            UserProfileVM vm = new UserProfileVM();
            vm.Profile = _profile.Get(id);
            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = "Study, Teacher")]
        public IActionResult CreateProfile()
        {
            UserProfileVM vm = new UserProfileVM();
            vm.Group = _group.GetAll();
            return View(vm);
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult UpdateUser(int id)
        {
            var tempuser = _user.Get(id);
            return View(tempuser);
        }

        //Method Post

        [HttpPost]
        public async Task<IActionResult> Autorizations(User users)
        {
            var user = _auth.LogIn(users);
            if (user is null)
            {
                return RedirectToAction("Autorization");
            }
            await HttpContext.SignInAsync(user);
            HttpContext.Session.SetInt32("Id", _auth.Id);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateUser(User user)
        {
            _user.Create(user);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult UpdateUser(User newUser)
        {
            _user.Update(newUser);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult DeleteUser(int id)
        {
            _user.Delete(id);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateProfile(UserProfileVM newProfile)
        {
            newProfile.Profile.Id = (int)HttpContext.Session.GetInt32("Id");
            var files = HttpContext.Request.Form.Files.FirstOrDefault();
            if(files != null)
            {
                using(var stream = files.OpenReadStream())
                {
                    //_profile.Create(_convert.ConvetToProfile(newProfile.), stream);
                    _profile.Create(newProfile.Profile, stream);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult UpdateProfile(UserProfileVM newProfile)
        {
            newProfile.Profile.Id = (int)HttpContext.Session.GetInt32("Id");
            if (HttpContext.Request.Form.Files.Count == 0)
                _profile.Update(newProfile.Profile, null);
            else 
            {
                var files = HttpContext.Request.Form.Files.FirstOrDefault();
                if (files != null)
                {
                    using (var stream = files.OpenReadStream())
                    {
                        _profile.Update(newProfile.Profile, stream);
                    }
                }
            } 
            //естественно перепревкой на обработку делать валидацию.... или это на блл сделать!!??!??!?!
            return RedirectToAction("Index", "Home");
        }

        //-------------------------------------------------------------------------------------------

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeacherOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TeacherOnline.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/chats.css">
    <script src="https://kit.fontawesome.com/7e95b76a8d.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Преподаватель Online</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Teacher") || User.IsInRole("Study"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" id="text_color" asp-controller="Home" asp-action="UserList">Пользователи</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toogle" id="text_color" data-bs-toggle="dropdown">Предметы</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" id="text_color" asp-controller="Estimate" asp-action="Index">Отметки</a></li>
                                    <li><a class="dropdown-item" id="text_color" asp-controller="Subject" asp-action="Subject">Предметы</a></li>
                                    @if (User.IsInRole("Teacher"))
                                    {
                                        <li><a class="dropdown-item" id="text_color" asp-controller="Group" asp-action="Index">Группы</a></li>
                                        <li><a class="dropdown-item" id="text_color" asp-controller="Subject" asp-action="GroupInSub">Группа-предмет</a></li>
                                    }
                                </ul>
                            </li>
                        }
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" id="text_color" asp-controller="Users" asp-action="Registration">Добавить пользователя</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" id="text_color" asp-controller="Chat" asp-action="Users">Чат</a>
                            </li>     
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="text_color" data-bs-toggle="dropdown"><i class="fa-regular fa-user"></i></a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li><a class="dropdown-item" asp-controller="Users" asp-action="Autorization">Авторизация</a></li>
                                }
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @if(!User.IsInRole("Admin"))
                                    {
                                        <li><a class="dropdown-item" asp-controller="Users" asp-action="UserProfile">Профиль</a></li>
                                    }
                                    <li><a class="dropdown-item" href="/logout">Выйти</a></li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2023 - Дипломный проект <a asp-action="Help" asp-controller="Home">Помощь</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
@*    <script src="https://cdn.jsdelivr.net/npm/@@microsoft/signalr@7.0.5/dist/browser/signalr.min.js"></script>
*@    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>*@
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>