TeacherOnline/Controllers/ChatController.cs
using AutoMapper.Configuration.Annotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.BLL.SignalR;
using TeacherOnline.DAL;
using TeacherOnline.DAL.Entities;
using TeacherOnline.DTO.ViewModel;
using TeacherOnline.Models;

namespace TeacherOnline.Controllers
{
    public class ChatController : Controller
    {
        IProfile _profile;
        IChat _chat;
        IMessage _message;

        public ChatController(IProfile profile, IChat chat, IMessage message)
        {
            _profile = profile;
            _chat = chat;
            _message = message;
        }

        //-------------------------------------------------------------------------------------------
        //Method Get

        [HttpGet]
        public IActionResult Index(int id)
        {
            ViewData["Id"] = HttpContext.Session.GetInt32("Id");
            var chat = _chat.Get(id);
            return View(chat);
        }

        [HttpGet]
        public IActionResult Users()
        {
            var chat = _chat.Find(u => u.IdUser1 == (int)HttpContext.Session.GetInt32("Id")
            || u.IdUser2 == (int)HttpContext.Session.GetInt32("Id")).ToList();
            ViewData["Id"] = HttpContext.Session.GetInt32("Id");
            return View(chat);
        }


        [HttpPost]
        public IActionResult CreateRoom(int Id)
        {
            var chat = new Chat()
            {
                IdUser1 = (int)HttpContext.Session.GetInt32("Id"),
                IdUser2 = Id
            };
            var temp = _chat.Get(u=> (u.IdUser1 == Id ||  u.IdUser2 == Id) 
                        && (u.IdUser1 == (int)HttpContext.Session.GetInt32("Id") || u.IdUser2 == (int)HttpContext.Session.GetInt32("Id")));
            int id;
            if(temp == null)
            {
                id = _chat.Create(chat);
            }
            else
            {
                id = _chat.Get(temp.Id).Id;
            }
            return RedirectToAction("Index", new { id });
        }

        [HttpPost]
        public async  Task<IActionResult> SendMessage(int chatId,string message, [FromServices] IHubContext<ChatHub> chats)
        {
            //тут валидация должна быть.... или на фронте....
            var mes = new Message
            {
                IdAuthor = (int)HttpContext.Session.GetInt32("Id"),
                Message1 = message,
                IdChat = chatId,
                Time = DateTime.Now
            };
            var updateMes = _message.Create(mes);
            await chats.Clients.Group(chatId.ToString()).SendAsync("ReceiveMessage", new
            {
                Text = updateMes.Message1,
                Name = $"{updateMes.IdAuthorNavigation.LastName} {updateMes.IdAuthorNavigation.FirstName}" ,
                Timestamp = updateMes.Time.ToString("hh:mm dd.MM.yy")
            });
            return Ok();
        }


        //-------------------------------------------------------------------------------------------

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeacherOnline/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.DAL.Entities;
using TeacherOnline.DTO.ViewModel;
using File = TeacherOnline.DAL.Entities.File;

namespace TeacherOnline.Controllers
{
    public class FileController : Controller
    {
        IFile _file;
        IGroupsInSub _groupsInSub;
        IProfile _user;
        ISubject _sub;

        public FileController(IFile file, IGroupsInSub groupsInSub, IProfile profile, ISubject subject)
        {
            _file = file;
            _groupsInSub = groupsInSub;
            _user = profile;
            _sub = subject;
        }

        [HttpGet]
        public ActionResult Index(int id)
        {
            ViewData["Id"] = HttpContext.Session.GetInt32("Id").ToString();
            if(id == (int)HttpContext.Session.GetInt32("Id"))
            {
                FileVM vm = new FileVM();
                vm.user = _user.Get(id);
                vm.files = _file.GetAll().Where(u => u.IdUser == (int)HttpContext.Session.GetInt32("Id")).ToList();
                vm.subjects = _sub.GetAll().ToList();
                return View(vm);
            }
            else
            {
                FileVM vm = new FileVM();
                vm.user = _user.Get(id);
                vm.files = _file.GetAll().Where(u => u.IdUser == id).ToList();
                return View(vm);
            }
        }

        [HttpGet]
        public ActionResult UpdateFile(int id)
        {
            FileVM vm = new FileVM();
            vm.file = _file.Get(id);
            return View(vm);
        }

        [HttpGet]
        public ActionResult FileSub(int id)
        {
            FileVM vm = new FileVM();
            vm.files = _file.GetAll().Where(u => u.IdSub == id).ToList();
            vm.subject = _sub.Get(id);
            return View(vm);
        }

        [HttpGet]
        public JsonResult GetSubject()
        {
            var user = _user.Get((int)HttpContext.Session.GetInt32("Id"));
            if(user.Groups != null)
            {
                var list = _groupsInSub.Find(u => u.IdGroups == (int)user.Groups).Select(u => new SelectListItem
                {
                    Value = u.IdSubjectNavigation.Id.ToString(),
                    Text = u.IdSubjectNavigation.Name
                });
                return Json(list);
            }
            else
            {
                var list = _groupsInSub.Find(u => u.IdTeacher == user.Id).Select(u => new SelectListItem
                {
                    Value = u.IdSubjectNavigation.Id.ToString(),
                    Text = u.IdSubjectNavigation.Name
                });
                return Json(list);
            }
        }

        [HttpPost]
        public IActionResult CreateFile(FileVM vm)
        {
            var item = vm.file;
            var file = HttpContext.Request.Form.Files.FirstOrDefault();
            if (file != null && file.Length > 0)
            {
                using (var stream = file.OpenReadStream())
                {
                    if (stream.Length > 0 && stream != null)
                    {
                        using (var memorystream = new MemoryStream())
                        {
                            item.Name = file.FileName;
                            item.TypeFiles = file.ContentType;
                            item.IdUser = (int)HttpContext.Session.GetInt32("Id");
                            stream.CopyTo(memorystream);
                            item.Files = memorystream.ToArray();
                            _file.Create(item);
                        }
                    }
                }
            }
            else NotFound("Нет файла"); //throw new Exception("Ошибка файла!");
            return RedirectToAction("Index", new { id = (int)HttpContext.Session.GetInt32("Id") });
        }

        [HttpPost]
        public ActionResult UpdateFile(FileVM item)
        {
            //_file.Delete(item.Id);
            //сначало удалить прошлый, а потом залить новый... а хотя тут же перезатирается
            var file = HttpContext.Request.Form.Files.FirstOrDefault();
            if (file != null && file.Length > 0)
            {
                using (var stream = file.OpenReadStream())
                {
                    if (stream.Length > 0 && stream != null)
                    {
                        using (var memorystream = new MemoryStream())
                        {
                            item.file.Name = file.FileName;
                            item.file.TypeFiles = file.ContentType;
                            stream.CopyTo(memorystream);
                            item.file.Files = memorystream.ToArray();
                            _file.Update(item.file);
                        }
                    }
                    else throw new Exception("Ошибка файла! ");
                }
            }
            else
            {
                _file.Update(item.file);
            }
            return RedirectToAction("Index", new { id = (int)HttpContext.Session.GetInt32("Id") });
        }

        [HttpPost]
        public ActionResult DeleteFile(int id)
        {
            _file.Delete(id);
            return RedirectToAction("Index", new { id = (int)HttpContext.Session.GetInt32("Id") });
        }

        [HttpPost]
        public ActionResult DownloadFile(int id)
        {
            var file = _file.Get(id);
            if(file != null)
            {
                return new FileContentResult(file.Files, file.TypeFiles)
                {
                    FileDownloadName = file.Name
                };
            }
            else
            {
                return NotFound();
            }
        }
    }
}

TeacherOnline/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using TeacherOnline.Models;
using TeacherOnline.DAL.Entities;
using TeacherOnline.BLL.Interfaces;
using TeacherOnline.DTO.ViewModel;
using TeacherOnline.DTO;

namespace TeacherOnline.Controllers
{
    public class UsersController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        IUser _user;
        IProfile _profile;
        IAuth _auth;
        IGroup _group;
        IConvertModels _convert;

        public UsersController(ILogger<HomeController> logger, IUser user, IProfile profile, IAuth auth, IGroup group, IConvertModels convert)
        {
            _logger = logger;
            _user = user;
            _profile = profile;
            _auth = auth;
            _group = group;
            _convert = convert;
        }

        //-------------------------------------------------------------------------------------------
        //Method Get

        [HttpGet]
        public IActionResult Autorization()
        {

            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Study, Teacher")] //тут же добавиться только авторизированным пользователям
        public  IActionResult UserProfile()
        {
            UserProfileVM vm = new UserProfileVM();
            vm.Group = _group.GetAll();
            vm.Profile = _profile.Get((int)HttpContext.Session.GetInt32("Id"));
            if (vm.Profile is null) return RedirectToAction("CreateProfile");
            return View(vm);
        }

        [HttpGet]
        public IActionResult CheckProfile(int id)
        {
            ViewData["Id"] = (int)HttpContext.Session.GetInt32("Id");
            UserProfileVM vm = new UserProfileVM();
            vm.Profile = _profile.Get(id);
            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = "Study, Teacher")]
        public IActionResult CreateProfile()
        {
            UserProfileVM vm = new UserProfileVM();
            vm.Group = _group.GetAll();
            return View(vm);
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult UpdateUser(int id)
        {
            var tempuser = _user.Get(id);
            return View(tempuser);
        }

        //Method Post

        [HttpPost]
        public async Task<IActionResult> Autorizations(User users)
        {
            var user = _auth.LogIn(users);
            if (user is null)
            {
                return RedirectToAction("Autorization");
            }
            await HttpContext.SignInAsync(user);
            HttpContext.Session.SetInt32("Id", _auth.Id);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateUser(User user)
        {
            _user.Create(user);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult UpdateUser(User newUser)
        {
            _user.Update(newUser);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult DeleteUser(int id)
        {
            _user.Delete(id);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult CreateProfile(UserProfileVM newProfile)
        {
            newProfile.Profile.Id = (int)HttpContext.Session.GetInt32("Id");
            var files = HttpContext.Request.Form.Files.FirstOrDefault();
            if(files != null)
            {
                using(var stream = files.OpenReadStream())
                {
                    //_profile.Create(_convert.ConvetToProfile(newProfile.), stream);
                    _profile.Create(newProfile.Profile, stream);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult UpdateProfile(UserProfileVM newProfile)
        {
            newProfile.Profile.Id = (int)HttpContext.Session.GetInt32("Id");
            if (HttpContext.Request.Form.Files.Count == 0)
                _profile.Update(newProfile.Profile, null);
            else 
            {
                var files = HttpContext.Request.Form.Files.FirstOrDefault();
                if (files != null)
                {
                    using (var stream = files.OpenReadStream())
                    {
                        _profile.Update(newProfile.Profile, stream);
                    }
                }
            } 
            //естественно перепревкой на обработку делать валидацию.... или это на блл сделать!!??!??!?!
            return RedirectToAction("Index", "Home");
        }

        //-------------------------------------------------------------------------------------------

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeacherOnline/Views/Users/AccessDenied.cshtml
@{
}

<h1>Доступ к данной странице недоступен!</h1>

TeacherOnline/Views/Users/Autorization.cshtml
@{
    ViewData["Title"] = "Авторизация";
}
@model TeacherOnline.DAL.Entities.User
<h2>@ViewData["Title"]</h2>


<link rel="stylesheet" href="/css/site.css" />
<form asp-controller="Users" asp-action="Autorizations" method="post">
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Логин</label>
        <input required max="20" type="text" class="form-control" id="exampleInputEmail1" asp-for="Login">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Пароль</label>
        <input required max="18" type="password" class="form-control" id="exampleInputPassword1" asp-for="Password">
      </div>
      <button type="submit" class="btn btn-outline-success">Войти</button>
</form>

TeacherOnline/Views/Users/CheckProfile.cshtml
@{
    ViewData["Title"] = "Профиль";
}
@using TeacherOnline.DTO.ViewModel;
@{
    string x, y;
    string date = "";
    if (Model.Profile.Date.Month < 10) 
    @*вот тут ошибка, возвращает нул, хотя должна быть дата.... писец*@
    {
        x = "0" + Model.Profile.Date.Month;
        if (Model.Profile.Date.Day < 10)
        {
            y = "0" + Model.Profile.Date.Day;
            date = Model.Profile.Date.Year + "-" + x + "-" + y;
        }
        else
        { date = Model.Profile.Date.Year + "-" + x + "-" + Model.Profile.Date.Day; }

    }
    else if (Model.Profile.Date.Day < 10)
    {
        y = "0" + Model.Profile.Date.Day;
        date = Model.Profile.Date.Year + "-" + Model.Profile.Date.Month + "-" + y;
    }
}

@model UserProfileVM;

<h2>@ViewData["Title"]</h2>

    <a class="btn btn-outline-success" asp-controller="File" asp-action="Index" asp-route-id="@Model.Profile.Id">Файлы</a>
    @if(Model.Profile.IdNavigation.Rank == "Study" || Model.Profile.Id == (int)ViewData["Id"] && Model.Profile.IdNavigation.Rank != "Teacher")
    {
        <a class="btn btn-outline-success" asp-controller="Estimate" asp-action="GetStats" asp-route-id="@Model.Profile.Id">Статистика по предметам</a>
    }
    @if(Model.Profile.Id != (int)ViewData["Id"]){

        <form asp-controller="Chat" asp-action="CreateRoom" asp-route-id="@Model.Profile.Id">
            <button type="submit" class="btn btn-outline-success">Написать</button>
        </form>
    }
<div class="row g-3" style="width:70vw">
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Фамилия</label>
            <input type="text" disabled class="form-control" id="inputFIO" placeholder="Иванов" value="@Model.Profile.LastName" asp-for="@Model.Profile.LastName">
        </div>
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Имя</label>
            <input type="text" disabled class="form-control" id="inputFIO" placeholder="Иван" value="@Model.Profile.FirstName" asp-for="@Model.Profile.FirstName">
        </div>
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Отчетсво</label>
            <input type="text" disabled class="form-control" id="inputFIO" placeholder="Иванович" value="@Model.Profile.Otchestvo" asp-for="@Model.Profile.Otchestvo">
        </div>
        <div class="col-md-3">
            <label for="inputDataHB" class="form-label">День рождения</label>
            <input type="date" disabled class="form-control" id="inputDataHB" value="@date" asp-for="@Model.Profile.Date">
        </div>
        @if (Model.Profile.IdNavigation.Rank != "Teacher")
        {
            <div class="col-md-3">
                <label for="inputDepartment" class="form-label">Группа</label>
                <select disabled class="form-select" asp-for="@Model.Profile.Groups">
                    <option value="@Model.Profile.GroupsNavigation?.Id">@Model.Profile.GroupsNavigation?.Name</option>
                </select>
            </div>
        }
        <div class="col-md-3">
            <label for="inputNumber" class="form-label">О себе</label>
            <input type="text" disabled class="form-control" id="inputNumber" value="@Model.Profile.About" asp-for="@Model.Profile.About">
        </div>
        <div class="row">
            <div class="col-md-5">
                <label for="formFile" class="form-label">Фото</label>
                <img style='width:120px; height:120px; margin:6px' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Profile.Photo))" />
            </div>
        </div>
</div>

TeacherOnline/Views/Users/CreateProfile.cshtml
@using TeacherOnline.DTO.ViewModel;
@{
    ViewData["Title"] = "Создание профиля";
}
@model UserProfileVM;

<h2>@ViewData["Title"]</h2>

<!-- g-* это размер отступов между элементами...

снизу - пример на создание профайла для пользователя админом.... просто пусть будет
-->
<form class="row g-3" style="width:1000px" enctype="multipart/form-data" method="post" asp-controller="Users" asp-action="CreateProfile">
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Фамилия</label>
            <input required type="text" class="form-control" id="inputFIO" placeholder="Иванов" asp-for="@Model.Profile.LastName">
        </div>
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Имя</label>
        <input required type="text" class="form-control" id="inputFIO" placeholder="Иван" asp-for="@Model.Profile.FirstName">
        </div>
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Отчетсво</label>
        <input required type="text" class="form-control" id="inputFIO" placeholder="Иванович" asp-for="@Model.Profile.Otchestvo">
        </div>
        <div class="col-md-3">
            <label for="inputDataHB" class="form-label">День рождения</label>
        <input required type="date" class="form-control" id="inputDataHB" asp-for="@Model.Profile.Date">
        </div>
        @if(!User.IsInRole("Teacher"))
        {
            <div class="col-md-3">
                <label for="inputDepartment" class="form-label">Группа</label>
                <select required class="form-select" asp-for="@Model.Profile.Groups">
                    @foreach(var item in Model.Group)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>    
        }
        <div class="col-md-12">
            <label for="inputNumber" class="form-label">О себе</label>
        <input required type="text" class="form-control" id="inputNumber" asp-for="@Model.Profile.About">
        </div>
        <div class="row">
            <div class="col-md-5">
                <label for="formFile" class="form-label">Загрузить фото</label>
                <input required class="form-control" type="file" id="formFile" accept="image/*" asp-for="@Model.Profile.Photo">
            </div>
        </div>
        <div class="col-md-12">
            <button type="submit" class="btn btn-outline-success">Создать профиль</button>
        </div>
    </form>

TeacherOnline/Views/Users/Registration.cshtml
@{
    ViewData["Title"] = "Регистрация";
}
@model TeacherOnline.DAL.Entities.User

<h2>@ViewData["Title"]</h2>
<form asp-controller="Users" asp-action="CreateUser" method="post" accept-charset="utf-8">
      <div class="mb-3">
        <label for="InputLogin" class="form-label">Логин</label>
        <input required max="20" type="text" class="form-control" id="exampleInputEmail1" asp-for="@Model.Login">
        <div id="emailHelp" class="form-text">Никому не сообщайте свой логин</div>
        <label for="exampleInputPassword1" class="form-label">Пароль</label>
        <input required minlength="8" max="18" type="password" class="form-control" id="exampleInputPassword1" asp-for="@Model.Password">
        <div id="passwordHelpBlock" class="form-text">
            Ваш пароль должен состоять из 8-18 символов, содержать буквы и цифры и не должен содержать пробелов,эмодзи.
        </div>
        <label for="InputEmail" class="form-label">Почта</label>
        <input required max="30" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" asp-for="@Model.Email">
        <div id="emailHelp" class="form-text">Мы данные о вашей почте никому не передаём</div>
        <label for="exampleInputEmail1" class="form-label">Тип пользователя</label>
        <select class="form-select" aria-label="rank" asp-for="@Model.Rank">
            <option selected value="Study">Студент</option>
            <option value="Admin">Админ</option>
            <option value="Teacher">Преподаватель</option>
        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">Создать пользователя</button>
</form>

TeacherOnline/Views/Users/UpdateUser.cshtml
@{
    ViewData["Title"] = "Обновить пользователя";
}
@model TeacherOnline.DAL.Entities.User

<h2>@ViewData["Title"]</h2>
<form asp-controller="Users" asp-action="UpdateUser" method="post" accept-charset="utf-8">
    @*@foreach(var item in Model){*@
        @*if(item.Id.ToString() == ViewData["idUser"]?.ToString()){*@
      <div class="mb-3">
        <label for="InputLogin" class="form-label">Логин</label>
            <input required type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="@Model.Login" name="Login">
        <div id="emailHelp" class="form-text">Никому не сообщайте свой логин</div>
        <label for="exampleInputPassword1" class="form-label">Пароль</label>
            <input required type="password" class="form-control" id="exampleInputPassword1" value="@Model.Password" name="Password">
        <div id="passwordHelpBlock" class="form-text">
            Ваш пароль должен состоять из 8-20 символов, содержать буквы и цифры и не должен содержать пробелов,эмодзи.
        </div>
        <label for="InputEmail" class="form-label">Почта</label>
            <input required type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="@Model.Email" name="Email">
        <div id="emailHelp" class="form-text">Мы данные о вашей почте никому не передаём</div>
        <label for="exampleInputEmail1" class="form-label">Тип пользователя</label>
            <select class="form-select" aria-label="rank" asp-for="@Model.Rank">
            @if (Model.Rank == "Study")
            {
                <option selected value="Study">Студент</option>
                <option value="Admin">Админ</option>
                <option value="Teacher">Преподаватель</option>
            }
            else if (Model.Rank == "Admin")
            {
                <option selected value="Admin">Админ</option>
                <option value="Teacher">Преподаватель</option>
                <option value="Study">Студент</option>
            }
            else
            {
                <option selected value="Teacher">Преподаватель</option>
                <option value="Admin">Админ</option>
                <option value="Study">Студент</option>
            }
        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">Обновить пользователя</button>
      
</form>

TeacherOnline/Views/Users/UserProfile.cshtml
@{
    ViewData["Title"] = "Профиль";
}
@using TeacherOnline.DTO.ViewModel;
@{
    string x, y;
    string date = "";
    if (Model.Profile.Date.Month < 10) 
    @*вот тут ошибка, возвращает нул, хотя должна быть дата.... писец*@
    {
        x = "0" + Model.Profile.Date.Month;
        if (Model.Profile.Date.Day < 10)
        {
            y = "0" + Model.Profile.Date.Day;
            date = Model.Profile.Date.Year + "-" + x + "-" + y;
        }
        else
        { date = Model.Profile.Date.Year + "-" + x + "-" + Model.Profile.Date.Day; }

    }
    else if (Model.Profile.Date.Day < 10)
    {
        y = "0" + Model.Profile.Date.Day;
        date = Model.Profile.Date.Year + "-" + Model.Profile.Date.Month + "-" + y;
    }
}

@model UserProfileVM;

    

<h2>@ViewData["Title"]</h2>


<!-- g-* это размер отступов между элементами...

снизу - пример на создание профайла для пользователя админом.... просто пусть будет
-->
<a class="btn btn-outline-success" asp-controller="File" asp-action="Index" asp-route-id="@Model.Profile.Id">Файлы</a>
@if (!User.IsInRole("Teacher"))
{
    <a class="btn btn-outline-success" asp-controller="Estimate" asp-action="GetStats" asp-route-id="@Model.Profile.Id">Статистика по предметам</a>
}

<form class="row g-3" style="width:70vw" asp-controller="Users" asp-action="UpdateProfile" enctype="multipart/form-data" method="post">
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Фамилия</label>
            <input required type="text" class="form-control" id="inputFIO" placeholder="Иванов" value="@Model.Profile.LastName" asp-for="@Model.Profile.LastName">
        </div>
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Имя</label>
            <input required type="text" class="form-control" id="inputFIO" placeholder="Иван" value="@Model.Profile.FirstName" asp-for="@Model.Profile.FirstName">
        </div>
        <div class="col-md-3">
            <label for="inputFIO" class="form-label">Отчетсво</label>
            <input required type="text" class="form-control" id="inputFIO" placeholder="Иванович" value="@Model.Profile.Otchestvo" asp-for="@Model.Profile.Otchestvo">
        </div>
        <div class="col-md-3">
            <label for="inputDataHB" class="form-label">День рождения</label>
            <input required type="date" class="form-control" id="inputDataHB" value="@date" asp-for="@Model.Profile.Date">
        </div>
        @if (!User.IsInRole("Teacher"))
        {
            <div class="col-md-3">
                <label for="inputDepartment" class="form-label">Группа</label>
                <select required class="form-select" asp-for="@Model.Profile.Groups">
                    @foreach (var item in Model.Group)
                    {
                        @if(Model.Profile.Groups == item.Id)
                        {
                            <option value="@item.Id">@item.Name</option>
                            continue;
                        }
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
        }
        <div class="col-md-12">
            <label for="inputNumber" class="form-label">О себе</label>
            <input required type="text" class="form-control" id="inputNumber" value="@Model.Profile.About" asp-for="@Model.Profile.About">
        </div>
        <div class="row">
            <div class="col-md-5">
                <label for="formFile" class="form-label">Загрузить фото</label>
                <input class="form-control" type="file" id="formFile" asp-for="@Model.Profile.Photo">
                <img style='width:120px; height:120px; margin-top:5px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Profile.Photo))" />
            </div>
        </div>
        <div class="col-md-12">
            <button type="submit" class="btn btn-outline-success">Сохранить данные</button>
        </div>
</form>